<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 6</h2></center>

## Compare SQL and Python

In [1]:
import pandas as pd

#### Define connection to the server with Py_MSSql module

In [2]:
import sys
sys.path.append('Modules/')
from Py_MSSql import Py_MSSql

In [3]:
server = "localhost\\SQLEXPRESS;Trusted_Connection=True;"#" Integrated Security=True;"
database = 'TutorialDB'

py_mssql = Py_MSSql(server=server,database=database)

## Import Data

In [4]:
# Pandas
df = pd.read_csv('Fert_data.csv')

In [5]:
country_sub_reg = [
    ['country', 'subregion'],
    ['Kenya', 'East Africa'],
    ['Liberia', 'West Africa'],
    ['Mali', 'West Africa']
]
df_sr = pd.DataFrame(country_sub_reg[1:],columns=country_sub_reg[0])
df_sr

   country    subregion
0    Kenya  East Africa
1  Liberia  West Africa
2     Mali  West Africa

In [6]:
data = [
    ['country', 'region', 'tfr', 'contraceptors'],    
    ['USA', 'North.Amer', 1.77, 20],
    ['UK', 'Europe', 1.79, 23],
    ['Bangladesh', 'Asia', 5.5, 40],
    ['Thailand', 'Asia', 2.3, 68],
    ['Mali', 'Africa', 6.80, 5]
]
df1 = pd.DataFrame(data[1:], columns=data[0])

In [7]:
# SQL
# In sql can import from csv

tbl_name = 'fert_data'
py_mssql.drop_table_if_exist(tbl_name)
py_mssql.create_tbl_from_df(df,tbl_name)
py_mssql.insert_into_tbl_from_df(df,tbl_name)

IF OBJECT_ID('dbo.fert_data', 'U') IS NOT NULL DROP TABLE dbo.fert_data
CREATE TABLE fert_data (country VARCHAR(30), region VARCHAR(20), tfr NUMERIC(18,10), contraceptors NUMERIC(18,10))
?,?,?,?, 35
INSERT QUERY:INSERT INTO fert_data (country, region, tfr, contraceptors) VALUES(?,?,?,?)

True

In [8]:
# SQL 
# Create country_sub_region table (in sql can import from csv)
tbl_name = 'country_sub_region'
py_mssql.drop_table_if_exist(tbl_name)
py_mssql.create_tbl_from_df(df_sr,tbl_name)
py_mssql.insert_into_tbl_from_df(df_sr,tbl_name)

IF OBJECT_ID('dbo.country_sub_region', 'U') IS NOT NULL DROP TABLE dbo.country_sub_region
CREATE TABLE country_sub_region (country VARCHAR(14), subregion VARCHAR(22))
?,?, 18
INSERT QUERY:INSERT INTO country_sub_region (country, subregion) VALUES(?,?)

True

In [9]:
# SQL 
# Create country_sub_region table (in sql can import from csv)
tbl_name = 'fert_data_1'
py_mssql.drop_table_if_exist(tbl_name)
py_mssql.create_tbl_from_df(df1,tbl_name)
py_mssql.insert_into_tbl_from_df(df1,tbl_name)

IF OBJECT_ID('dbo.fert_data_1', 'U') IS NOT NULL DROP TABLE dbo.fert_data_1
CREATE TABLE fert_data_1 (country VARCHAR(20), region VARCHAR(20), tfr NUMERIC(18,10), contraceptors NUMERIC(18,10))
?,?,?,?, 35
INSERT QUERY:INSERT INTO fert_data_1 (country, region, tfr, contraceptors) VALUES(?,?,?,?)

True

## Select

#### Select all columns

In [10]:
# Python

df
# df.head()
# df.tail()

            country      region  tfr  contraceptors
0          Botswana      Africa  4.8             35
1           Burundi      Africa  6.5              9
2          Cameroon      Africa  5.9             16
3             Ghana      Africa  6.1             13
4             Kenya      Africa  6.5             27
5           Liberia      Africa  6.4              6
6              Mali      Africa  6.8              5
7          Mauitius      Africa  2.2             75
8             Niger      Africa  7.3              4
9           Nigeria      Africa  5.7              6
10          Senegal      Africa  6.4             12
11            Sudan      Africa  4.8              9
12        Swaziland      Africa  5.0             21
13         Tanzania      Africa  6.1             10
14             Togo      Africa  6.1             12
15           Uganda      Africa  7.2              5
16           Zambia      Africa  6.3             15
17         Zimbabwe      Africa  5.3             45
18       Bangladesh        Asia  5.5             40
19            China        Asia  2.5             72
20            India        Asia  4.3             45
21        Indonesia        Asia  3.0             50
22     Korea.Rep.of        Asia  1.7             77
23         Pakistan        Asia  5.2             12
24      Philippines        Asia  4.3             34
25        Sri.Lanka        Asia  2.7             62
26         Thailand        Asia  2.3             68
27          Vietnam        Asia  3.9             53
28           Belize  Latin.Amer  4.5             47
29          Bolivia  Latin.Amer  4.9             32
30           Brazil  Latin.Amer  3.6             66
31         Columbia  Latin.Amer  2.8             66
32       Costa.Rica  Latin.Amer  3.6             70
33     Dom.Republic  Latin.Amer  3.3             56
34          Ecuador  Latin.Amer  3.8             53
35      El.Salvador  Latin.Amer  4.6             47
36        Guatemala  Latin.Amer  5.6             23
37            Haiti  Latin.Amer  6.0             10
38          Jamaica  Latin.Amer  2.9             55
39           Mexico  Latin.Amer  4.0             55
40           Panama  Latin.Amer  4.0             58
41         Paraguay  Latin.Amer  4.6             48
42             Peru  Latin.Amer  3.5             59
43  Trinidad.Tobago  Latin.Amer  3.1             54
44            Egypt   Near.East  4.6             40
45           Jordan   Near.East  5.5             35
46          Morocco   Near.East  4.0             42
47          Tunisia   Near.East  4.3             51
48           Turkey   Near.East  3.4             60
49            Yemen   Near.East  7.0              7

#### Select specific columns

In [11]:
# Python
df[['country','tfr']]

            country  tfr
0          Botswana  4.8
1           Burundi  6.5
2          Cameroon  5.9
3             Ghana  6.1
4             Kenya  6.5
5           Liberia  6.4
6              Mali  6.8
7          Mauitius  2.2
8             Niger  7.3
9           Nigeria  5.7
10          Senegal  6.4
11            Sudan  4.8
12        Swaziland  5.0
13         Tanzania  6.1
14             Togo  6.1
15           Uganda  7.2
16           Zambia  6.3
17         Zimbabwe  5.3
18       Bangladesh  5.5
19            China  2.5
20            India  4.3
21        Indonesia  3.0
22     Korea.Rep.of  1.7
23         Pakistan  5.2
24      Philippines  4.3
25        Sri.Lanka  2.7
26         Thailand  2.3
27          Vietnam  3.9
28           Belize  4.5
29          Bolivia  4.9
30           Brazil  3.6
31         Columbia  2.8
32       Costa.Rica  3.6
33     Dom.Republic  3.3
34          Ecuador  3.8
35      El.Salvador  4.6
36        Guatemala  5.6
37            Haiti  6.0
38          Jamaica  2.9
39           Mexico  4.0
40           Panama  4.0
41         Paraguay  4.6
42             Peru  3.5
43  Trinidad.Tobago  3.1
44            Egypt  4.6
45           Jordan  5.5
46          Morocco  4.0
47          Tunisia  4.3
48           Turkey  3.4
49            Yemen  7.0

## Where

In [12]:
# Python
mask1 = df['tfr'] >= 5.5
mask2 = df['tfr'] <= 7
mask3 = df['region'] != 'Africa'

df[mask1 & mask2 & mask3]

# df[(df['tfr'] >= 5.5) & (df['tfr'] <= 7) & (df['region'] != 'Africa')]

       country      region  tfr  contraceptors
18  Bangladesh        Asia  5.5             40
36   Guatemala  Latin.Amer  5.6             23
37       Haiti  Latin.Amer  6.0             10
45      Jordan   Near.East  5.5             35
49       Yemen   Near.East  7.0              7

## Insert

In [13]:
# Python
# In Pandas, We can use tools such as concat() or append() to perform this task

data = {
    'country': 'Japan', 
    'region': 'Asia', 
    'tfr':1.73, 
    'contraceptors' : 73
}
df = df.append(data, ignore_index=True)
df.tail(3)

   country     region   tfr  contraceptors
48  Turkey  Near.East  3.40             60
49   Yemen  Near.East  7.00              7
50   Japan       Asia  1.73             73

## Update

In [14]:
# Python
# df.loc[row_indexer,col_indexer] = value

mask = df['country'] == 'Mauitius'
df[mask]

# df.loc[mask, 'contraceptors'] = 65
# df.loc[mask]

    country  region  tfr  contraceptors
7  Mauitius  Africa  2.2             75

## Delete

In [15]:
df = df.loc[df['region'] != 'Asia']
df

            country      region  tfr  contraceptors
0          Botswana      Africa  4.8             35
1           Burundi      Africa  6.5              9
2          Cameroon      Africa  5.9             16
3             Ghana      Africa  6.1             13
4             Kenya      Africa  6.5             27
5           Liberia      Africa  6.4              6
6              Mali      Africa  6.8              5
7          Mauitius      Africa  2.2             75
8             Niger      Africa  7.3              4
9           Nigeria      Africa  5.7              6
10          Senegal      Africa  6.4             12
11            Sudan      Africa  4.8              9
12        Swaziland      Africa  5.0             21
13         Tanzania      Africa  6.1             10
14             Togo      Africa  6.1             12
15           Uganda      Africa  7.2              5
16           Zambia      Africa  6.3             15
17         Zimbabwe      Africa  5.3             45
28           Belize  Latin.Amer  4.5             47
29          Bolivia  Latin.Amer  4.9             32
30           Brazil  Latin.Amer  3.6             66
31         Columbia  Latin.Amer  2.8             66
32       Costa.Rica  Latin.Amer  3.6             70
33     Dom.Republic  Latin.Amer  3.3             56
34          Ecuador  Latin.Amer  3.8             53
35      El.Salvador  Latin.Amer  4.6             47
36        Guatemala  Latin.Amer  5.6             23
37            Haiti  Latin.Amer  6.0             10
38          Jamaica  Latin.Amer  2.9             55
39           Mexico  Latin.Amer  4.0             55
40           Panama  Latin.Amer  4.0             58
41         Paraguay  Latin.Amer  4.6             48
42             Peru  Latin.Amer  3.5             59
43  Trinidad.Tobago  Latin.Amer  3.1             54
44            Egypt   Near.East  4.6             40
45           Jordan   Near.East  5.5             35
46          Morocco   Near.East  4.0             42
47          Tunisia   Near.East  4.3             51
48           Turkey   Near.East  3.4             60
49            Yemen   Near.East  7.0              7

## Joins

In [16]:
df
# df_sr

            country      region  tfr  contraceptors
0          Botswana      Africa  4.8             35
1           Burundi      Africa  6.5              9
2          Cameroon      Africa  5.9             16
3             Ghana      Africa  6.1             13
4             Kenya      Africa  6.5             27
5           Liberia      Africa  6.4              6
6              Mali      Africa  6.8              5
7          Mauitius      Africa  2.2             75
8             Niger      Africa  7.3              4
9           Nigeria      Africa  5.7              6
10          Senegal      Africa  6.4             12
11            Sudan      Africa  4.8              9
12        Swaziland      Africa  5.0             21
13         Tanzania      Africa  6.1             10
14             Togo      Africa  6.1             12
15           Uganda      Africa  7.2              5
16           Zambia      Africa  6.3             15
17         Zimbabwe      Africa  5.3             45
28           Belize  Latin.Amer  4.5             47
29          Bolivia  Latin.Amer  4.9             32
30           Brazil  Latin.Amer  3.6             66
31         Columbia  Latin.Amer  2.8             66
32       Costa.Rica  Latin.Amer  3.6             70
33     Dom.Republic  Latin.Amer  3.3             56
34          Ecuador  Latin.Amer  3.8             53
35      El.Salvador  Latin.Amer  4.6             47
36        Guatemala  Latin.Amer  5.6             23
37            Haiti  Latin.Amer  6.0             10
38          Jamaica  Latin.Amer  2.9             55
39           Mexico  Latin.Amer  4.0             55
40           Panama  Latin.Amer  4.0             58
41         Paraguay  Latin.Amer  4.6             48
42             Peru  Latin.Amer  3.5             59
43  Trinidad.Tobago  Latin.Amer  3.1             54
44            Egypt   Near.East  4.6             40
45           Jordan   Near.East  5.5             35
46          Morocco   Near.East  4.0             42
47          Tunisia   Near.East  4.3             51
48           Turkey   Near.East  3.4             60
49            Yemen   Near.East  7.0              7

In [17]:
pd.merge(df, df_sr, on='country', how='inner')

   country  region  tfr  contraceptors    subregion
0    Kenya  Africa  6.5             27  East Africa
1  Liberia  Africa  6.4              6  West Africa
2     Mali  Africa  6.8              5  West Africa

## Union

In [18]:
df_dupli = pd.concat([df1, df])
df_dupli

            country      region   tfr  contraceptors
0               USA  North.Amer  1.77             20
1                UK      Europe  1.79             23
2        Bangladesh        Asia  5.50             40
3          Thailand        Asia  2.30             68
4              Mali      Africa  6.80              5
0          Botswana      Africa  4.80             35
1           Burundi      Africa  6.50              9
2          Cameroon      Africa  5.90             16
3             Ghana      Africa  6.10             13
4             Kenya      Africa  6.50             27
5           Liberia      Africa  6.40              6
6              Mali      Africa  6.80              5
7          Mauitius      Africa  2.20             75
8             Niger      Africa  7.30              4
9           Nigeria      Africa  5.70              6
10          Senegal      Africa  6.40             12
11            Sudan      Africa  4.80              9
12        Swaziland      Africa  5.00             21
13         Tanzania      Africa  6.10             10
14             Togo      Africa  6.10             12
15           Uganda      Africa  7.20              5
16           Zambia      Africa  6.30             15
17         Zimbabwe      Africa  5.30             45
28           Belize  Latin.Amer  4.50             47
29          Bolivia  Latin.Amer  4.90             32
30           Brazil  Latin.Amer  3.60             66
31         Columbia  Latin.Amer  2.80             66
32       Costa.Rica  Latin.Amer  3.60             70
33     Dom.Republic  Latin.Amer  3.30             56
34          Ecuador  Latin.Amer  3.80             53
35      El.Salvador  Latin.Amer  4.60             47
36        Guatemala  Latin.Amer  5.60             23
37            Haiti  Latin.Amer  6.00             10
38          Jamaica  Latin.Amer  2.90             55
39           Mexico  Latin.Amer  4.00             55
40           Panama  Latin.Amer  4.00             58
41         Paraguay  Latin.Amer  4.60             48
42             Peru  Latin.Amer  3.50             59
43  Trinidad.Tobago  Latin.Amer  3.10             54
44            Egypt   Near.East  4.60             40
45           Jordan   Near.East  5.50             35
46          Morocco   Near.East  4.00             42
47          Tunisia   Near.East  4.30             51
48           Turkey   Near.East  3.40             60
49            Yemen   Near.East  7.00              7

In [19]:
# we will get duplicate rows 
mask = df_dupli['country'] == 'Mali'
df_dupli[mask]

  country  region  tfr  contraceptors
4    Mali  Africa  6.8              5
6    Mali  Africa  6.8              5

In [20]:
# We can drop duplicate records using drop_duplicates()
pd.concat([df1, df]).drop_duplicates()

            country      region   tfr  contraceptors
0               USA  North.Amer  1.77             20
1                UK      Europe  1.79             23
2        Bangladesh        Asia  5.50             40
3          Thailand        Asia  2.30             68
4              Mali      Africa  6.80              5
0          Botswana      Africa  4.80             35
1           Burundi      Africa  6.50              9
2          Cameroon      Africa  5.90             16
3             Ghana      Africa  6.10             13
4             Kenya      Africa  6.50             27
5           Liberia      Africa  6.40              6
7          Mauitius      Africa  2.20             75
8             Niger      Africa  7.30              4
9           Nigeria      Africa  5.70              6
10          Senegal      Africa  6.40             12
11            Sudan      Africa  4.80              9
12        Swaziland      Africa  5.00             21
13         Tanzania      Africa  6.10             10
14             Togo      Africa  6.10             12
15           Uganda      Africa  7.20              5
16           Zambia      Africa  6.30             15
17         Zimbabwe      Africa  5.30             45
28           Belize  Latin.Amer  4.50             47
29          Bolivia  Latin.Amer  4.90             32
30           Brazil  Latin.Amer  3.60             66
31         Columbia  Latin.Amer  2.80             66
32       Costa.Rica  Latin.Amer  3.60             70
33     Dom.Republic  Latin.Amer  3.30             56
34          Ecuador  Latin.Amer  3.80             53
35      El.Salvador  Latin.Amer  4.60             47
36        Guatemala  Latin.Amer  5.60             23
37            Haiti  Latin.Amer  6.00             10
38          Jamaica  Latin.Amer  2.90             55
39           Mexico  Latin.Amer  4.00             55
40           Panama  Latin.Amer  4.00             58
41         Paraguay  Latin.Amer  4.60             48
42             Peru  Latin.Amer  3.50             59
43  Trinidad.Tobago  Latin.Amer  3.10             54
44            Egypt   Near.East  4.60             40
45           Jordan   Near.East  5.50             35
46          Morocco   Near.East  4.00             42
47          Tunisia   Near.East  4.30             51
48           Turkey   Near.East  3.40             60
49            Yemen   Near.East  7.00              7

## Group by

In [21]:
# we have a groupby() function that helps us in summarizing data along a specific column
df.groupby('region').agg({'tfr': 'mean', 'contraceptors': 'size'}).round(2)

             tfr  contraceptors
region
Africa      5.86             18
Latin.Amer  4.05             16
Near.East   4.80              6