<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 4+5</h2></center>

In [ ]:
import pandas as pd
import datetime

# Import data source

In [ ]:
# Import csv file
# Watch sample from the data

df = pd.read_csv ('police.csv')

# >> Use parameter: parse_dates=[] - parse as a single date column
# df = pd.read_csv ('police.csv', parse_dates=['stop_date'])

# pd.to_datetime(df['stop_date'] )
# df['stop_date'] = pd.to_datetime(df['stop_date'])
df.head(3)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop
0,2005-02-01,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Ticket,False,341.0,0-15 Min,False
1,2005-01-18,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Ticket,False,161.0,0-15 Min,False

In [ ]:
# Check column names and types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  datetime64[ns]
 1   stop_time           91741 non-null  object
 2   county_name         0 non-null      float64
 3   driver_gender       86406 non-null  object
 4   driver_age_raw      86414 non-null  float64
 5   driver_age          86120 non-null  float64
 6   driver_race         86408 non-null  object
 7   violation_raw       86408 non-null  object
 8   violation           86408 non-null  object
 9   search_conducted    91741 non-null  bool
 10  search_type         3196 non-null   object
 11  stop_outcome        86408 non-null  object
 12  is_arrested         86408 non-null  object
 13  ticket_amount       1082 non-null   float64
 14  stop_duration       86408 non-null  object
 15  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), datetime64[ns](1), float64(4), object(9)
memory usage: 10.0+ MB

In [ ]:
# Series.dt() = Accessor object for datetimelike properties of the Series values.

df['stop_date'].dt.year
# df['stop_date'].dt.month
# df['stop_date'].dt.day
# df['stop_date'].dt.week
# df['stop_date'].dt.weekday   # Monday = 0, Sunday=6

df['stop_year'] = df['stop_date'].dt.year

# Viewing and inspecting data

In [1]:
df.columns

NameError: ignored

In [ ]:
# Generate descriptive statistics 
# Use method to_csv ('file_name.csv') to save the result as csv file in the same folder as the notebook

df.describe()
# df['driver_age'].describe()
# df['driver_age'].describe().to_csv('driver age statistics.csv')

       county_name  driver_age_raw    driver_age  ticket_amount     stop_year
count          0.0    86414.000000  86120.000000    1082.000000  91741.000000
mean           NaN     1970.491228     34.011333     219.540665   2010.267699
std            NaN      110.914909     12.738564      71.287997      3.029080
min            NaN        0.000000     15.000000     101.000000   2005.000000
25%            NaN     1967.000000     23.000000     158.250000   2008.000000
50%            NaN     1980.000000     31.000000     215.000000   2010.000000
75%            NaN     1987.000000     43.000000     283.750000   2013.000000
max            NaN     8801.000000     99.000000     349.000000   2015.000000

### 1. Missing values

#### Check for missing values

In [ ]:
# Check how much data in each column
# >> county_name: all values are Null 
# >> search_conducted: some values missing

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  datetime64[ns]
 1   stop_time           91741 non-null  object
 2   county_name         0 non-null      float64
 3   driver_gender       86406 non-null  object
 4   driver_age_raw      86414 non-null  float64
 5   driver_age          86120 non-null  float64
 6   driver_race         86408 non-null  object
 7   violation_raw       86408 non-null  object
 8   violation           86408 non-null  object
 9   search_conducted    91741 non-null  bool
 10  search_type         3196 non-null   object
 11  stop_outcome        86408 non-null  object
 12  is_arrested         86408 non-null  object
 13  ticket_amount       1082 non-null   float64
 14  stop_duration       86408 non-null  object
 15  drugs_related_stop  91741 non-null  bool
 16  stop_year           91741 non-null  int64
dtypes: bool(2), datetime64[ns](1), float64(4), int64(1), object(9)
memory usage: 10.7+ MB

#### Drop empty columns

In [ ]:
# >> Drop column
# >> Use parameter: inplace=True
# >> When to save backup of the data, and how?

df.drop(columns='county_name')
# df.drop(columns='county_name', inplace=True)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop,stop_year
0,2005-02-01,1:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Ticket,False,341.0,0-15 Min,False,2005
1,2005-01-18,8:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Ticket,False,161.0,0-15 Min,False,2005
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,NaN,16-30 Min,False,2005
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,NaN,0-15 Min,False,2015
91737,2015-12-31,20:35,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,NaN,0-15 Min,False,2015
91738,2015-12-31,20:45,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,NaN,0-15 Min,False,2015
91739,2015-12-31,21:42,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015
91740,2015-12-31,22:46,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015

In [ ]:
# Check why there are less data in "search_type" column
mask = df['search_type'].isnull()
df[mask]

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop,stop_year
0,2005-02-01,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Ticket,False,341.0,0-15 Min,False,2005
1,2005-01-18,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Ticket,False,161.0,0-15 Min,False,2005
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,NaN,16-30 Min,False,2005
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,NaN,0-15 Min,False,2015
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,NaN,0-15 Min,False,2015
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,NaN,0-15 Min,False,2015
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015

#### Check for Null values

In [ ]:
# dropna(): drop rows or columns with NaN
# >> Use parameter: axis=0 : drop rows with NaN, axis=1 : drop columns with NaN
#                   thresh=number : require that many non-NA values
#                   how='all' : at least one NA or all NA 
#                   subset=['col_1', 'col_2' ...] : check only in these columns for NaN values
#                   inplace=True : save the changes on the df


df.count()
# df.dropna(axis=1)
# df.dropna(axis=1).count()
# df.dropna(axis=0, thresh=8)
# df.dropna(how='all')
# df.dropna(subset=['stop_date', 'violation_raw', 'violation'])


# df.dropna(subset=['stop_date', 'violation_raw', 'violation'], inplace=True)
# df.dropna(axis=1,how='all', inplace=True)

# df

stop_date             91741
stop_time             91741
county_name               0
driver_gender         86406
driver_age_raw        86414
driver_age            86120
driver_race           86408
violation_raw         86408
violation             86408
search_conducted      91741
search_type            3196
stop_outcome          86408
is_arrested           86408
ticket_amount          1082
stop_duration         86408
drugs_related_stop    91741
stop_year             91741
dtype: int64

#### Fill Null values

In [ ]:
# fillna(value) : Fill NA/NaN values
# >> Use parameter: inplace=True : save the changes on the df
# Example: row number: 146, 281

df.fillna(-999)

# mask = df['driver_age' ].isnull()
# df [mask]

# df['driver_age'].mean()

# df['driver_age'].fillna(round(df['driver_age'].mean()))
# df['driver_age'].fillna(round(df['driver_age'].mean())).loc[146]
# df['driver_age'].fillna(round(df['driver_age'].mean()), inplace=True)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop,stop_year
0,2005-02-01,1:55,-999.0,M,1985.0,20.0,White,Speeding,Speeding,False,-999,Ticket,False,341.0,0-15 Min,False,2005
1,2005-01-18,8:15,-999.0,M,1965.0,40.0,White,Speeding,Speeding,False,-999,Citation,False,-999.0,0-15 Min,False,2005
2,2005-01-23,23:15,-999.0,M,1972.0,33.0,White,Speeding,Speeding,False,-999,Ticket,False,161.0,0-15 Min,False,2005
3,2005-02-20,17:15,-999.0,M,1986.0,19.0,White,Call for Service,Other,False,-999,Arrest Driver,True,-999.0,16-30 Min,False,2005
4,2005-03-14,10:00,-999.0,F,1984.0,21.0,White,Speeding,Speeding,False,-999,Citation,False,-999.0,0-15 Min,False,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,-999.0,M,1986.0,29.0,White,Speeding,Speeding,False,-999,Warning,False,-999.0,0-15 Min,False,2015
91737,2015-12-31,20:35,-999.0,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,-999,Warning,False,-999.0,0-15 Min,False,2015
91738,2015-12-31,20:45,-999.0,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,-999,Warning,False,-999.0,0-15 Min,False,2015
91739,2015-12-31,21:42,-999.0,M,1993.0,22.0,White,Speeding,Speeding,False,-999,Citation,False,-999.0,0-15 Min,False,2015
91740,2015-12-31,22:46,-999.0,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,-999,Citation,False,-999.0,0-15 Min,False,2015

## Grouping

#### Group object
When using group by() method, we Create categories that based on common values in certain column or multiple columns based on DataFrame

In [ ]:
# Create groupby object and store in in variable
g_violation = df.groupby('violation_raw')

In [ ]:
# The groupby object is DataFrameGroupBy type
type(g_violation)

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
# Number of groups
len (g_violation)

# Can get the same result with the function nunique()
# df['violation_raw'].nunique()

12

In [ ]:
# How many rows in each group category
g_violation.size()

violation_raw
APB                                    79
Call for Service                     1298
Equipment/Inspection Violation      11020
Motorist Assist/Courtesy              203
Other Traffic Violation             16224
Registration Violation               3432
Seatbelt Violation                   2952
Special Detail/Directed Patrol       2455
Speeding                            48463
Suspicious Person                      56
Violation of City/Town Ordinance      211
Warrant                                15
dtype: int64

In [ ]:
# Show the first/last row in each group category
g_violation.first()
# g_violation.last()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop,stop_year
violation_raw,,,,,,,,,,,,,,,,
APB,2005-05-10,16:10,NaN,M,1979.0,26.0,White,Other,False,Incident to Arrest,Citation,False,NaN,0-15 Min,False,2005
Call for Service,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Other,False,Incident to Arrest,Arrest Driver,True,NaN,16-30 Min,False,2005
Equipment/Inspection Violation,2005-03-23,9:45,NaN,M,1982.0,23.0,Black,Equipment,False,Probable Cause,Citation,False,NaN,0-15 Min,False,2005
Motorist Assist/Courtesy,2005-12-10,7:50,NaN,M,0.0,32.0,White,Other,False,Incident to Arrest,No Action,False,NaN,0-15 Min,False,2005
Other Traffic Violation,2005-07-08,16:50,NaN,M,1953.0,52.0,White,Moving violation,False,"Incident to Arrest,Protective Frisk",Citation,False,NaN,0-15 Min,False,2005
Registration Violation,2005-03-10,23:20,NaN,M,1954.0,51.0,White,Registration/plates,False,Incident to Arrest,Citation,False,NaN,0-15 Min,False,2005
Seatbelt Violation,2012-01-12,10:20,NaN,M,1970.0,42.0,Black,Seat belt,False,"Probable Cause,Protective Frisk",Citation,False,NaN,0-15 Min,False,2012
Special Detail/Directed Patrol,2005-04-10,0:36,NaN,M,1961.0,44.0,White,Other,False,Protective Frisk,Arrest Driver,True,NaN,30+ Min,False,2005
Speeding,2005-02-01,1:55,NaN,M,1985.0,20.0,White,Speeding,False,Incident to Arrest,Ticket,False,341.0,0-15 Min,False,2005
Suspicious Person,2005-07-10,23:30,NaN,M,1986.0,19.0,White,Other,True,Probable Cause,Arrest Passenger,True,NaN,16-30 Min,True,2005
Violation of City/Town Ordinance,2005-05-10,17:00,NaN,M,1985.0,20.0,White,Other,False,Incident to Arrest,Citation,False,NaN,0-15 Min,False,2005
Warrant,2006-04-26,13:45,NaN,M,1978.0,28.0,Hispanic,Other,False,Incident to Arrest,Arrest Driver,True,NaN,0-15 Min,False,2006

In [ ]:
# Returns divtionary with key=group, value = list of all indexes of rows in the group
g_violation.groups
# g_violation.groups['Speeding']

{'APB': Int64Index([  154,   223,  1925,  2163,  2196,  3897,  4774,  5904,  7910,
              8740,  9144,  9932, 10467, 12047, 12049, 12569, 16719, 18943,
             19348, 19955, 22322, 25379, 26245, 26944, 28951, 30717, 31825,
             31941, 33317, 34606, 35966, 36037, 36117, 38273, 38545, 39087,
             43500, 44489, 45091, 46866, 47427, 49503, 52717, 54613, 56227,
             56250, 60233, 61715, 63119, 63896, 64278, 65569, 66137, 66434,
             68399, 68866, 69193, 69454, 69671, 71884, 73018, 75122, 75413,
             75704, 76309, 76406, 76507, 80506, 81568, 83770, 85295, 86399,
             86508, 86563, 86839, 88638, 89906, 90055, 91672],
            dtype='int64'),
 'Call for Service': Int64Index([    3,   153,   242,   290,   293,   557,   691,   705,   856,
              1316,
             ...
             91485, 91486, 91504, 91544, 91605, 91607, 91608, 91609, 91630,
             91683],
            dtype='int64', length=1298),
 'Equipment/Inspection Violation': Int64Index([    5,    17,    35,    40,    41,    46,    49,    99,   106,
               108,
             ...
             91668, 91684, 91687, 91693, 91694, 91704, 91709, 91729, 91730,
             91737],
            dtype='int64', length=11020),
 'Motorist Assist/Courtesy': Int64Index([  331,   363,   706,   993,  1003,  1508,  1583,  1760,  1856,
              2023,
             ...
             87921, 88140, 88269, 88272, 88296, 88858, 89592, 90280, 90362,
             91176],
            dtype='int64', length=203),
 'Other Traffic Violation': Int64Index([   21,    22,    24,    30,    33,    42,    45,   118,   138,
               142,
             ...
             91682, 91688, 91690, 91696, 91703, 91706, 91707, 91718, 91719,
             91738],
            dtype='int64', length=16224),
 'Registration Violation': Int64Index([  113,   129,   186,   260,   317,   353,   434,   449,   463,
               465,
             ...
             91629, 91634, 91645, 91654, 91685, 91686, 91692, 91705, 91723,
             91733],
            dtype='int64', length=3432),
 'Seatbelt Violation': Int64Index([65415, 65418, 65419, 65560, 65607, 65667, 65673, 65691, 65721,
             65726,
             ...
             91613, 91635, 91653, 91661, 91666, 91669, 91689, 91691, 91708,
             91716],
            dtype='int64', length=2952),
 'Special Detail/Directed Patrol': Int64Index([  116,   117,   201,   289,  1336,  1899,  3613,  6837,  7043,
              7218,
             ...
             90752, 90764, 90765, 90768, 90945, 90963, 91166, 91421, 91426,
             91698],
            dtype='int64', length=2455),
 'Speeding': Int64Index([    0,     1,     2,     4,     6,     7,     8,     9,    10,
                11,
             ...
             91726, 91727, 91728, 91731, 91732, 91734, 91735, 91736, 91739,
             91740],
            dtype='int64', length=48463),
 'Suspicious Person': Int64Index([  219,  2709,  4054,  4143,  8223, 13150, 14725, 18143, 20631,
             23340, 23494, 26279, 27212, 30142, 36345, 37587, 38116, 38163,
             38958, 40721, 40900, 41250, 42458, 43052, 43229, 44016, 44269,
             46820, 48036, 49460, 52915, 53417, 57411, 58235, 59148, 62843,
             63460, 63534, 65700, 66921, 69977, 72119, 72615, 77318, 78100,
             78244, 78573, 78841, 79095, 79919, 81767, 83031, 83819, 85991,
             88816, 90674],
            dtype='int64'),
 'Violation of City/Town Ordinance': Int64Index([  156,  2571,  3124,  3361,  3626,  3771,  3886,  4204,  4597,
              6044,
             ...
             85021, 85631, 86274, 87127, 87409, 87437, 88721, 90436, 91192,
             91351],
            dtype='int64', length=211),
 'Warrant': Int64Index([ 6032,  7306, 16048, 21265, 22359, 24941, 25101, 39150, 43117,
             48917, 69217, 78034, 87167, 88244, 90614],
            dtype='int64')}

In [ ]:
# Returns rows from this group category
g_violation.get_group('Speeding')

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop,stop_year
0,2005-02-01,1:55,NaN,M,1985.0,20.0,White,Speeding,False,NaN,Ticket,False,341.0,0-15 Min,False,2005
1,2005-01-18,8:15,NaN,M,1965.0,40.0,White,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,False,NaN,Ticket,False,161.0,0-15 Min,False,2005
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
6,2005-01-04,17:30,NaN,M,1969.0,36.0,White,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91734,2015-12-31,20:20,NaN,M,1993.0,22.0,White,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015
91735,2015-12-31,20:25,NaN,M,1992.0,23.0,Hispanic,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,False,NaN,Warning,False,NaN,0-15 Min,False,2015
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2015

In [ ]:
# Returns computed max/min/mean/count/sum of values within each group

g_violation['driver_age'].max()
# g_violation['driver_age'].min()
# g_violation['driver_age'].mean()
# g_violation['violation'].count()
# g_violation['ticket_amount'].sum()
# g_violation[['driver_age','ticket_amount']].max()
# g_violation['driver_age'].describe()

violation_raw
APB                                 72.0
Call for Service                    87.0
Equipment/Inspection Violation      89.0
Motorist Assist/Courtesy            70.0
Other Traffic Violation             99.0
Registration Violation              74.0
Seatbelt Violation                  77.0
Special Detail/Directed Patrol      78.0
Speeding                            90.0
Suspicious Person                   69.0
Violation of City/Town Ordinance    75.0
Warrant                             63.0
Name: driver_age, dtype: float64

In [ ]:
# Create group with main category and sub category

g_gender_violation = df.groupby(['driver_gender','violation_raw'])

In [ ]:
# Rturns computed max/min/mean/count/sum of values within each group - multiple columns

g_gender_violation[['driver_age','ticket_amount']].mean()

                                                driver_age  ticket_amount
driver_gender violation_raw
F             APB                                34.142857            NaN
              Call for Service                   32.863741            NaN
              Equipment/Inspection Violation     31.521739            NaN
              Motorist Assist/Courtesy           36.355932            NaN
              Other Traffic Violation            33.954930            NaN
              Registration Violation             32.850791            NaN
              Seatbelt Violation                 30.124409            NaN
              Special Detail/Directed Patrol     36.794393            NaN
              Speeding                           32.529023     214.771978
              Suspicious Person                  35.466667            NaN
              Violation of City/Town Ordinance   34.391304            NaN
              Warrant                            31.500000            NaN
M             APB                                36.929825            NaN
              Call for Service                   34.702924            NaN
              Equipment/Inspection Violation     31.857210            NaN
              Motorist Assist/Courtesy           36.592308            NaN
              Other Traffic Violation            36.653404            NaN
              Registration Violation             32.783023            NaN
              Seatbelt Violation                 32.776867            NaN
              Special Detail/Directed Patrol     43.744474            NaN
              Speeding                           34.000729     222.210894
              Suspicious Person                  32.410256            NaN
              Violation of City/Town Ordinance   35.454545            NaN
              Warrant                            31.545455            NaN

## Group Aggregations

#### agg() method
Using group by with agg() to enable multiple columns + multiple aggregations at once

In [ ]:
# Choose only some of the columns

g_violation[['driver_age', 'ticket_amount']]

In [ ]:
# Calculate the three aggregations ('size', 'sum', 'mean') for all the columns
g_violation[['driver_age', 'ticket_amount']].agg(['size', 'sum', 'mean'])

                                 driver_age                        \
                                       size        sum       mean
violation_raw
APB                                      79     2822.0  36.179487
Call for Service                       1298    43901.0  34.084627
Equipment/Inspection Violation        11020   349819.0  31.781503
Motorist Assist/Courtesy                203     6902.0  36.518519
Other Traffic Violation               16224   583844.0  36.120020
Registration Violation                 3432   112416.0  32.803035
Seatbelt Violation                     2952    95073.0  32.206301
Special Detail/Directed Patrol         2455   102887.0  43.430561
Speeding                              48463  1621549.0  33.530097
Suspicious Person                        56     1796.0  33.259259
Violation of City/Town Ordinance        211     7432.0  35.222749
Warrant                                  15      473.0  31.533333

                                 ticket_amount
                                          size       sum        mean
violation_raw
APB                                         79       0.0         NaN
Call for Service                          1298       0.0         NaN
Equipment/Inspection Violation           11020       0.0         NaN
Motorist Assist/Courtesy                   203       0.0         NaN
Other Traffic Violation                  16224       0.0         NaN
Registration Violation                    3432       0.0         NaN
Seatbelt Violation                        2952       0.0         NaN
Special Detail/Directed Patrol            2455       0.0         NaN
Speeding                                 48463  237423.0  219.632747
Suspicious Person                           56       0.0         NaN
Violation of City/Town Ordinance           211       0.0         NaN
Warrant                                     15       0.0         NaN

In [ ]:
# Calculate different aggregations on different columns

g_violation.agg({'driver_age' : ['min', 'mean', 'max'],
                 'ticket_amount' : ['mean', 'sum']})

                                 driver_age                  ticket_amount  \
                                        min       mean   max          mean
violation_raw
APB                                    18.0  36.179487  72.0           NaN
Call for Service                       16.0  34.084627  87.0           NaN
Equipment/Inspection Violation         16.0  31.781503  89.0           NaN
Motorist Assist/Courtesy               17.0  36.518519  70.0           NaN
Other Traffic Violation                15.0  36.120020  99.0           NaN
Registration Violation                 16.0  32.803035  74.0           NaN
Seatbelt Violation                     17.0  32.206301  77.0           NaN
Special Detail/Directed Patrol         17.0  43.430561  78.0           NaN
Speeding                               15.0  33.530097  90.0    219.632747
Suspicious Person                      18.0  33.259259  69.0           NaN
Violation of City/Town Ordinance       18.0  35.222749  75.0           NaN
Warrant                                20.0  31.533333  63.0           NaN


                                       sum
violation_raw
APB                                    0.0
Call for Service                       0.0
Equipment/Inspection Violation         0.0
Motorist Assist/Courtesy               0.0
Other Traffic Violation                0.0
Registration Violation                 0.0
Seatbelt Violation                     0.0
Special Detail/Directed Patrol         0.0
Speeding                          237423.0
Suspicious Person                      0.0
Violation of City/Town Ordinance       0.0
Warrant                                0.0

In [ ]:
# Short writing example
df.groupby(['driver_gender','violation_raw']).agg({'driver_age' : ['min', 'mean', 'max']})

# df.groupby(['driver_gender','violation_raw']).agg({'driver_age' : ['min', 'mean', 'max']}).to_csv('driver gender violation.csv')

                                               driver_age
                                                      min       mean   max
driver_gender violation_raw
F             APB                                    19.0  34.142857  54.0
              Call for Service                       16.0  32.863741  74.0
              Equipment/Inspection Violation         16.0  31.521739  89.0
              Motorist Assist/Courtesy               18.0  36.355932  70.0
              Other Traffic Violation                15.0  33.954930  99.0
              Registration Violation                 16.0  32.850791  72.0
              Seatbelt Violation                     17.0  30.124409  71.0
              Special Detail/Directed Patrol         19.0  36.794393  67.0
              Speeding                               16.0  32.529023  84.0
              Suspicious Person                      20.0  35.466667  69.0
              Violation of City/Town Ordinance       18.0  34.391304  59.0
              Warrant                                24.0  31.500000  47.0
M             APB                                    18.0  36.929825  72.0
              Call for Service                       16.0  34.702924  87.0
              Equipment/Inspection Violation         16.0  31.857210  85.0
              Motorist Assist/Courtesy               17.0  36.592308  65.0
              Other Traffic Violation                15.0  36.653404  94.0
              Registration Violation                 16.0  32.783023  74.0
              Seatbelt Violation                     17.0  32.776867  77.0
              Special Detail/Directed Patrol         17.0  43.744474  78.0
              Speeding                               15.0  34.000729  90.0
              Suspicious Person                      18.0  32.410256  61.0
              Violation of City/Town Ordinance       18.0  35.454545  75.0
              Warrant                                20.0  31.545455  63.0

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Home Practice 4</h1></center>

1. Please show the amount of traffic offenses for each year. Sort the results in descending order

2. Continuing from the previous question, present each year:
   * The amount of traffic offenses
   * The average amount of the reports
   * Total annual report amount

   To make the results more readable, use the astype() method: astype(wanted_data_type), in order for the results to be integers
   
#### We will now examine the differences between the sexes in relation to traffic offenses, in the last year (2015)
3. What is the total amount of offenses for men and what is the amount for women?


4. Compare the types of offenses between men and women, and present the following information:
   * Average age
   * How many tickets were given
   * Total amount of tickets
   * How many offenses
   
   
5. Explore the data with the tools we have learned so far, and present 3 insights about the data when comparing women and men

#### Home Pactice 4 - Solution
1. Please show the amount of traffic offenses for each year. Sort the results in descending order

2. Continuing from the previous question, present each year:
   * The amount of traffic offenses
   * The average amount of the reports
   * Total annual report amount

   To make the results more readable, use the astype() method: astype(wanted_data_type), in order for the results to be integers
   
#### We will now examine the differences between the sexes in relation to traffic offenses, in the last year (2015)
3. What is the total amount of offenses for men and what is the amount for women?


4. Compare the types of offenses between men and women, and present the following information:
   * Average age
   * How many tickets were given
   * Total amount of tickets
   * How many offenses
   
   
5. Explore the data with the tools we have learned so far, and present 3 insights about the data when comparing women and men

In [ ]:
df = pd.read_csv ('police.csv', parse_dates=['stop_date'])
df['stop_year'] = df['stop_date'].dt.year

In [ ]:
# 1

# Option 1 - save the group in variable
g_year = df.groupby ('stop_year')
result = g_year['violation'].count()
result.sort_values(ascending=False)

In [ ]:
# Option 2 - method chaining, no need to save group in variable if its for quick calculation
df.groupby ('stop_year')['violation'].count().sort_values(ascending=False)

In [ ]:
# 2
df.groupby ('stop_year').agg({'violation_raw' : 'count',
                              'ticket_amount' : ['mean', 'sum']}).astype('int') #.transpose()

In [ ]:
# 3
# Preparinf the data
mask = df['stop_year'] == 2015
df_last = df[mask]
df_last.head(3)

In [ ]:
df_last.groupby ('driver_gender')['violation_raw'].count()

In [ ]:
# 4
df_last.groupby (['driver_gender','violation_raw']).agg({'driver_age' : 'mean', 
                                                         'ticket_amount' : ['count', 'sum'], 
                                                         'violation' : 'count'})