<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 4+5</h2></center>

## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Functions

#### User defines function - basics

In [2]:
# Define function

def my_func():
    
    print('Hello !')

In [3]:
# Calling the function

my_func()

Hello !

In [4]:
# function can receive parameters

def my_func(x):
    print(x)

In [5]:
my_func(5)

5

## Local and Global variables

In [6]:
# variable scope - difference between local and global variable
# when x is out of the function - its global variable
# when x is defined in a function - its local variable(even if we have global variable with the same name)

def example1():
    x = 5
    print(x)

In [7]:
# Calling the function

example1()

5

In [8]:
# x is a local variable that exist only in the example1 function scope
# When we try to call the x variable, its not exist outside the function, so we get error
x

NameError: name 'x' is not defined

In [10]:
y = 1      # global variable

def example1(y):
    print(y)
    
def example2():
    print(y)

In [11]:
example1(10)

example2()

10
1

## Lambda Function

Lambda function is anonymous function which involve small and concise syntax

In [12]:
# Regular user defined function

def identity_f(x):
    return x + 10

In [13]:
# lambda function

lambda a : a + 10

# identity_l = lambda a : a + 10

In [14]:
# Same result for both functions

identity_f(10)
# identity_l(10)

20

In [15]:
# Lambda function can get more than one input

my_func = lambda a, b, c : a + b + c

In [16]:
my_func(1, 2, 3)

6

## Combination of a Lambda and standart function

#### First we see the example

In [17]:
# A really cool use case of lambda expressions is within functions
# This function returns lambda expression

def my_func(n):
    return lambda a : a * n

In [18]:
my_doubler = my_func(2)
my_tripler = my_func(3)

In [19]:
my_doubler(11)

22

In [20]:
my_tripler(11)

33

#### Explanation

In [32]:
# Lets look on simple function
def exmple(n):
    return n + 10

In [33]:
# Lets call the function and save the result in variable
x = exmple(10)

In [34]:
# The value of x is the result of n+10 i.e. 10+10 i.e. 20
x

20

In [35]:
# my_doubler(2) gets the result value of: Lambda a: a * n
# n = 2
# So the value of my_doubler(2) is Lambda a: a * 2 >> its a function
my_doubler

In [36]:
# Since my_doubler is lambda function that receive the parameter a
# We can call my_doubler with a value and it will return the value * 2

my_doubler(10)

20

### Applying Functions(and lambda)

In [22]:
# Read csv file and show first 3 rows
df = pd.read_csv('police.csv')
df.head(3)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop
0,02/01/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Ticket,False,341.0,0-15 Min,False
1,18/01/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False
2,23/01/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Ticket,False,161.0,0-15 Min,False

In [23]:
# User defined function that receive age and return adult/young as outcome 
def is_adult(age):
    if age > 18:
        return 'adult'
    else:
        return 'young'
    
is_adult(23)

'adult'

In [24]:
# Call the function to test result
is_adult(df['driver_age'][0])

'adult'

In [25]:
# Check for rows that age less than 18
# Call the function to test result

df[ df['driver_age'] < 18].head(3)
# is_adult(df['driver_age'][39])

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop
39,30/09/2005,20:17,NaN,M,1988.0,17.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False
40,01/10/2005,0:00,NaN,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,NaN,16-30 Min,True
41,01/10/2005,0:00,NaN,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,NaN,30+ Min,True

#### Apply() Function

In [26]:
# Apply a function along an axis of the DataFrame
# Save results as new column

df['driver_age'].apply(is_adult)

# df['IsAdult'] = df['driver_age'].apply(is_adult)
# df.head(3)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop,IsAdult
0,02/01/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Ticket,False,341.0,0-15 Min,False,adult
1,18/01/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,adult
2,23/01/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Ticket,False,161.0,0-15 Min,False,adult

In [27]:
# Use apply with teh same functionality, using lambda function

df['driver_age'].apply(lambda x: 'adult' if x > 18 else 'young')
# df['IsAdult'] = df['age'].apply(lambda x: 'adult' if x>18 else 'young')

0        adult
1        adult
2        adult
3        adult
4        adult
         ...
91736    adult
91737    adult
91738    adult
91739    adult
91740    adult
Name: driver_age, Length: 91741, dtype: object

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Class Practice 4.2</h1></center>

1.  Create a function that implement the string method "split":
    * The function signature is:
      def split(string,by):
       
    * Without using the split method str.split()
    
    * You can use: data types, data structures, conditions, loops, functions.
      Use as many variables as you like to the function
    
    * The function should return a value that is equal to the value that string.split() would return

In [ ]:
# Function signature:
# string - the string to proccess
# by - the char to split the string vaeiable by

def split(string,by):
    ...

In [ ]:
# Call the function

split('Great.practice.!.!.!','.')
# Desired outcome: ['Great', 'practice', '!', '!', '!']

2. Write a Python function that takes a sequence of numbers and return True if all numbers are different from each other, otherwise return false

In [ ]:
# Function signature:

def all_digits_unique(numbers):
    # numbers - the sequence of numbers(list / tuple / ...)

In [ ]:
test1 = [1,2,1,2,3,4,5,6]
all_digits_unique(test1)

# Desired outcome: False

In [ ]:
test2 =(1,2,3,4)
all_digits_unique(test2)
# Desired outcome: True

3. Write a **Lambda** function that receives a word and returns it backwards(words in reverse order).

=========================================================================================

#### Pactice 4.2 - Solution
1.  Create a function that implement the string method "split":
    * The function signature is:
      def split(string,by):
       
    * Without using the split method str.split()
    
    * You can use: data types, data structures, conditions, loops, functions.
      Use as many variables as you like to the function
    
    * The function should return a value that is equal to the value that string.split() would return

In [28]:
# Option 1
def split(string, by=' '):
    
    values = ['']
        
    for letter in string:
        
        if letter != by:
            values[-1] += letter
        else:
            values.append('')
    
    if values[-1] == '':
        values.pop()
    
    return values

In [29]:
# Option 2
def split(string, by=''):
    result = []
    word = ''
    
    for letter in string:
        if letter == by:
            if word != '':
                result.append(word)
            word = ''
        else:
            word += letter
    
    if word != '':
        result.append(word) 
        
    return result

In [30]:
split('Great.practice.!.!.!','.')

['Great', 'practice', '!', '!', '!']

In [31]:
split('123 456 789 ')

['123 456 789 ']

2. Write a Python function that takes a sequence of numbers and return True if all numbers are different from each other, otherwise return false

In [32]:
def all_digits_unique(numbers):
    # `set` will only record unique elements.
    # We convert to a string and check if the unique
    # elements are the same number as the original elements.
    
    len_list = len(numbers)
    len_set = len( set(numbers) )
    return len_list == len_set

In [33]:
test1 = [1,2,1,2,3,4,5,6]
all_digits_unique(test1)

False

In [34]:
test2 =(1,2,3,4)
all_digits_unique(test2)

True

3. Write a **Lambda** function that receives a word and returns it backwards(words in reverse order)

In [35]:
reverse = lambda word : word[::-1]

In [36]:
reverse('!!enod lleW')

'Well done!!'