<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 2 + 3</h2></center>

## Pandas

In [1]:
# Import Pandas library
import pandas as pd

## Import data

Import data from csv file.
It is recommended to save the file in the same folder as your notebook

If saved in the same folder: 'file_name.csv'

If not saved in the same folder: r'full_path\file_name.csv':

        pd.read_csv (r'C:\Talia_Study\Data_Sets\netflix_titles.csv')

In [2]:
# Import data as DataFrame
pd.read_csv ('hotel_bookings.csv')

,reservation_no,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,12603,Resort Hotel,0,342,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
1,12604,Resort Hotel,0,737,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
2,12605,Resort Hotel,0,7,2015,July,27,1,0,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
3,12606,Resort Hotel,0,13,2015,July,27,1,0,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
4,12607,Resort Hotel,0,14,2015,July,27,1,0,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,03/07/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,131988,City Hotel,0,23,2017,August,35,30,2,5,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06/09/2017
119386,131989,City Hotel,0,102,2017,August,35,31,2,5,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07/09/2017
119387,131990,City Hotel,0,34,2017,August,35,31,2,5,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07/09/2017
119388,131991,City Hotel,0,109,2017,August,35,31,2,5,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07/09/2017
119389,131992,City Hotel,0,205,2017,August,35,29,2,7,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07/09/2017

In [3]:
# Import only one column as Pandas Series
# >> Check the differance with type () function
# >> index is automatically running number starts with 0

s = pd.read_csv ('hotel_bookings.csv', usecols=['arrival_date_month'], squeeze=True)

In [4]:
# Create another series from integer value
# Changing index to values in spacific column
int_s = pd.read_csv ('hotel_bookings.csv',usecols=['stays_in_week_nights','hotel'], 
                     squeeze=True, index_col='hotel')

## Attributes

With Attributes we can know information about the series components

In [5]:
# Array with all the values in the Series
s.values

array(['July', 'July', 'July', ..., 'August', 'August', 'August'],
      dtype=object)

In [6]:
# Description of the indexes
s.index

RangeIndex(start=0, stop=119390, step=1)

In [7]:
# Data type of the objects in the Series
s.dtypes

dtype('O')

## Viewing and Inspecting data

#### List of all methods and attributes available

In [8]:
# List of all the methods and attributes for this object
dir (s)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_convert_dtypes',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_find_valid_index',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iget_item_cache',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_ndarray_values',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

#### Basic info

In [9]:
# Show the content of first x rows
s.head(3)

0    July
1    July
2    July
Name: arrival_date_month, dtype: object

In [10]:
# Show the content of last x rows
s.tail(3)

119387    August
119388    August
119389    August
Name: arrival_date_month, dtype: object

In [11]:
# max value in the Series
int_s.max()

50

In [12]:
# Return the row number of the maximum value
int_s.argmax()

14038

In [13]:
# Return the index lable of the maximum value
int_s.idxmax()

'Resort Hotel'

In [14]:
# min value in the Series
int_s.min()

0

In [15]:
# Return the row number of the minimum value
int_s.argmin()

0

In [16]:
# Return the index lable of the minimum value
int_s.idxmin()

'Resort Hotel'

In [17]:
# Lenght od the Series
len (s)

119390

In [18]:
# Return boolean if values in the object are unique
s.is_unique

False

In [19]:
# Generate descriptive statistics
# >> check for both s and int_s
s.describe()

count     119390
unique        12
top       August
freq       13877
Name: arrival_date_month, dtype: object

In [20]:
# Get Series name
# >> can change Series name
s.name

'arrival_date_month'

In [21]:
# Return a Series containing counts of unique values.
# Use for categorial field
# Parameter: dropna=True (remove NaN), dropna=False (Don't remove NaN)
s.value_counts()

August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: arrival_date_month, dtype: int64

#### Sort

In [22]:
# Sort Series according to Series values
# >> parameters: ascending=False, inplace=True
s.sort_values ()

87641        April
87091        April
87090        April
87089        April
87088        April
           ...
8398     September
8397     September
8396     September
8404     September
98043    September
Name: arrival_date_month, Length: 119390, dtype: object

In [23]:
# sort Series according to Series index
# parameters: ascending=False, inplace=True
s.sort_index ()

0           July
1           July
2           July
3           July
4           July
           ...
119385    August
119386    August
119387    August
119388    August
119389    August
Name: arrival_date_month, Length: 119390, dtype: object

#### In keyword

In [24]:
# Check if value is in the Series values
# >> check if value is in the index: 34 in s
'April' in s.values

True

#### Locate data

In [25]:
# Return the row with the specified index lable or the location
# >> default value: default='Not Found'
int_s['Resort Hotel']

Resort Hotel     0
Resort Hotel     0
Resort Hotel     1
Resort Hotel     1
Resort Hotel     2
                ..
Resort Hotel     8
Resort Hotel     9
Resort Hotel    10
Resort Hotel    10
Resort Hotel    10
Name: stays_in_week_nights, Length: 40060, dtype: int64

In [26]:
# Returns the rows in the spacified *locations*: [start:stop:step]
s.iloc[840:845]
# int_s.iloc[840:845]

840      July
841      July
842    August
843    August
844    August
Name: arrival_date_month, dtype: object

In [27]:
# Returns the rows that their *lable index* is in the range [start:stop:step]
s.loc[840:843]
# int_s.loc['Resort Hotel']

840      July
841      July
842    August
843    August
Name: arrival_date_month, dtype: object

In [28]:
# Returns the rows in the locations list
s[  [1,840, 844, 2400]  ]

1          July
840        July
844      August
2400    October
Name: arrival_date_month, dtype: object

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Class Practice 2.2</h1></center>

1. From the hotel_bookings.csv file import column 'reservation_no' as index and 'stays_in_week_nights' into series name: 'ex_nights'

2. How many week nights were booked from the hotel?

3. What is the maximum week nights ordered?

4. What is the reservation number of the maximum week nights ordered?

5. Locate the reservation number you found in the previus section and check if you were correct

6. How many reservation ordered 15 week nights?

7. What are the top 3 amount of nights ordered?

8. What are the average nights ordered?

## DataFrame

Pandas matrix data structure

In [45]:
# Import data as DataFrame
df = pd.read_csv ('hotel_bookings.csv')

In [46]:
# Show top n rows
df.head(3)

,reservation_no,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,12603,Resort Hotel,0,342,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/2015
1,12604,Resort Hotel,0,737,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/2015
2,12605,Resort Hotel,0,7,2015,July,27,1,0,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,02/07/2015

#### Basic information

Most of the attributes and methods are working for both DataFrame and Series

In [47]:
# Return a tuple representing the dimensionality of the DataFrame
df.shape

(119390, 33)

In [278]:
# Generate descriptive statistics
df.describe ()

,reservation_no,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,...,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,72297.500000,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,...,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,34465.068657,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,...,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,12603.000000,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,42450.250000,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,72297.500000,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,102144.750000,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,131992.000000,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,...,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [279]:
# Print a concise summary of a DataFram
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   reservation_no                  119390 non-null  int64
 1   hotel                           119390 non-null  object
 2   is_canceled                     119390 non-null  int64
 3   lead_time                       119390 non-null  int64
 4   arrival_date_year               119390 non-null  int64
 5   arrival_date_month              119390 non-null  object
 6   arrival_date_week_number        119390 non-null  int64
 7   arrival_date_day_of_month       119390 non-null  int64
 8   stays_in_weekend_nights         119390 non-null  int64
 9   stays_in_week_nights            119390 non-null  int64
 10  adults                          119390 non-null  int64
 11  children                        119386 non-null  float64
 12  babies                          119390 non-null  int64
 13  meal                            119390 non-null  object
 14  country                         118902 non-null  object
 15  market_segment                  119390 non-null  object
 16  distribution_channel            119390 non-null  object
 17  is_repeated_guest               119390 non-null  int64
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  reserved_room_type              119390 non-null  object
 21  assigned_room_type              119390 non-null  object
 22  booking_changes                 119390 non-null  int64
 23  deposit_type                    119390 non-null  object
 24  agent                           103050 non-null  float64
 25  company                         6797 non-null    float64
 26  days_in_waiting_list            119390 non-null  int64
 27  customer_type                   119390 non-null  object
 28  adr                             119390 non-null  float64
 29  required_car_parking_spaces     119390 non-null  int64
 30  total_of_special_requests       119390 non-null  int64
 31  reservation_status              119390 non-null  object
 32  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(17), object(12)
memory usage: 30.1+ MB

In [51]:
# Return all the keys (all the columns header)
df.keys()

RangeIndex(start=0, stop=119390, step=1)

#### Show specific data

In [290]:
# Show one column from the DataFrame
df['country']

0         PRT
1         PRT
2         GBR
3         GBR
4         GBR
         ...
119385    BEL
119386    FRA
119387    DEU
119388    GBR
119389    DEU
Name: country, Length: 119390, dtype: object

#### Question: What is the average number of nights that customers book

* descriptive statistics on the nights ordered in week / weekend

* Are there any orders that have been canceled, or not executed?

In [298]:
# First lets view only the data that is relevant for us
# Shows only the columns that are in the list
sdf = df[     ['hotel', 'arrival_date_month', 'stays_in_weekend_nights','stays_in_week_nights', 'reservation_status']    ]

In [299]:
# Lets check what are the values in column reservation_status
df['reservation_status'].value_counts()

Check-Out    75166
Canceled     43017
No-Show       1207
Name: reservation_status, dtype: int64

In [311]:
# Filter the irrelevant records out of the table
sdf = sdf [sdf['reservation_status'] == 'Check-Out']

,hotel,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,reservation_status
0,Resort Hotel,July,0,0,Check-Out
1,Resort Hotel,July,0,0,Check-Out
2,Resort Hotel,July,0,1,Check-Out
3,Resort Hotel,July,0,1,Check-Out
4,Resort Hotel,July,0,2,Check-Out
...,...,...,...,...,...
119385,City Hotel,August,2,5,Check-Out
119386,City Hotel,August,2,5,Check-Out
119387,City Hotel,August,2,5,Check-Out
119388,City Hotel,August,2,5,Check-Out
119389,City Hotel,August,2,7,Check-Out

In [312]:
# Generate descriptive statistics on the remain records
sdf.describe()

       stays_in_weekend_nights  stays_in_week_nights
count             75166.000000          75166.000000
mean                  0.928971              2.464053
std                   0.993371              1.924803
min                   0.000000              0.000000
25%                   0.000000              1.000000
50%                   1.000000              2.000000
75%                   2.000000              3.000000
max                  19.000000             50.000000

In [321]:
# Sort the values
# >> It is not possible to get correct information because there are two columns with relevant data 
# >> should merged data into one new column
sdf.sort_values('stays_in_week_nights', ascending=False)

,hotel,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,reservation_status,total_nights
14038,Resort Hotel,July,19,50,Check-Out,69
14037,Resort Hotel,August,18,42,Check-Out,60
101794,City Hotel,September,16,41,Check-Out,57
33924,Resort Hotel,January,16,40,Check-Out,56
88017,City Hotel,March,14,35,Check-Out,49
...,...,...,...,...,...,...
36831,Resort Hotel,May,2,0,Check-Out,2
36832,Resort Hotel,May,2,0,Check-Out,2
36833,Resort Hotel,May,2,0,Check-Out,2
36834,Resort Hotel,May,1,0,Check-Out,1
0,Resort Hotel,July,0,0,Check-Out,0

#### Add new column to DataFrame

In [316]:
# Create new column for total_nights and update its value
sdf['total_nights'] = sdf['stays_in_weekend_nights'] + sdf['stays_in_week_nights']

In [320]:
# descriptive statistics on the updated DataFrame
# >> on specific column ['total_nights']
sdf.describe()

count    75166.000000
mean         3.393023
std          2.577671
min          0.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         69.000000
Name: total_nights, dtype: float64

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Class Practice 2.3</h1></center>

1. Import hotel_bookings.csv file into DataFrame name: 'df_hotel'


2. How many orders there are for each hotel?


3. Filter the records (rows), and show only the records whose arrival_date_month was July?


4. Continuing from the previous section, sort the results by 'adults' column (number of adults in the room) descending


5. **Advanced Exercise** -  Continuing from the previous section, show only columns: 'reservation_no', 'arrival_date_month', 'asults'

=========================================================================================

#### Pactice 2.2 - Solution
1. From the hotel_bookings.csv file import column 'reservation_no' as index and 'stays_in_week_nights' into series name: 'ex_nights'


2. How many week nights were booked from the hotel?


3. What is the maximum week nights ordered?


4. What is the reservation number of the maximum week nights ordered?


5. Locate the reservation number you found in the previus section and check if you were correct


6. How many reservation ordered 15 week nights?


7. What are the top 3 amount of nights ordered?


8. What are the average nights ordered?

In [30]:
# 1
ex_nights = pd.read_csv ('hotel_bookings.csv', 
                         usecols = ['reservation_no', 'stays_in_week_nights'],
                        index_col = 'reservation_no',
                        squeeze=True)
ex_nights

reservation_no
12603     0
12604     0
12605     1
12606     1
12607     2
         ..
131988    5
131989    5
131990    5
131991    5
131992    7
Name: stays_in_week_nights, Length: 119390, dtype: int64

In [31]:
# 2
ex_nights.sum ()

298511

In [32]:
# 3
ex_nights.max ()

50

In [42]:
# 4
ex_nights.idxmax()

26641

In [44]:
# 5
# Option 1
ex_nights.loc[26641]
# Option 2
ex_nights[26641]

50

In [36]:
# 6
ex_nights[ ex_nights == 15 ].count()

85

In [39]:
# 7
ex_nights.value_counts().head (3)

2    33684
1    30310
3    22258
Name: stays_in_week_nights, dtype: int64

In [46]:
# 8
ex_nights.mean()

2.500301532791691

#### Pactice 2.3 - Solution
1. Import hotel_bookings.csv file into DataFrame name: 'df_hotel'


2. How many orders there are for each hotel?


3. Filter the records (rows), and show only the records whose arrival_date_month was July?


4. Continuing from the previous section, sort the results by 'adults' column (number of adults in the room) descending


5. **Advanced Exercise** -  Continuing from the previous section, show only columns: 'reservation_no', 'arrival_date_month', 'asults'

In [47]:
# 1
df_hotel = pd.read_csv('hotel_bookings.csv')
df_hotel

,reservation_no,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,12603,Resort Hotel,0,342,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
1,12604,Resort Hotel,0,737,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
2,12605,Resort Hotel,0,7,2015,July,27,1,0,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
3,12606,Resort Hotel,0,13,2015,July,27,1,0,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
4,12607,Resort Hotel,0,14,2015,July,27,1,0,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,03/07/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,131988,City Hotel,0,23,2017,August,35,30,2,5,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06/09/2017
119386,131989,City Hotel,0,102,2017,August,35,31,2,5,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07/09/2017
119387,131990,City Hotel,0,34,2017,August,35,31,2,5,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07/09/2017
119388,131991,City Hotel,0,109,2017,August,35,31,2,5,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07/09/2017
119389,131992,City Hotel,0,205,2017,August,35,29,2,7,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07/09/2017

In [48]:
# 2
df_hotel['hotel'].value_counts()

City Hotel      79330
Resort Hotel    40060
Name: hotel, dtype: int64

In [54]:
# 3
mask = df_hotel['arrival_date_month'] == 'July'
df_hotel[mask]

,reservation_no,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,12603,Resort Hotel,0,342,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/2015
1,12604,Resort Hotel,0,737,2015,July,27,1,0,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,01/07/2015
2,12605,Resort Hotel,0,7,2015,July,27,1,0,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,02/07/2015
3,12606,Resort Hotel,0,13,2015,July,27,1,0,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,02/07/2015
4,12607,Resort Hotel,0,14,2015,July,27,1,0,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,03/07/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117737,130340,City Hotel,0,158,2017,July,31,31,3,6,...,No Deposit,NaN,NaN,0,Transient-Party,112.5,0,1,Check-Out,09/08/2017
117772,130375,City Hotel,0,158,2017,July,31,31,3,6,...,No Deposit,NaN,NaN,0,Transient-Party,132.5,0,1,Check-Out,09/08/2017
117821,130424,City Hotel,0,308,2017,July,30,25,4,12,...,No Deposit,9.0,NaN,0,Transient,107.1,0,1,Check-Out,10/08/2017
117822,130425,City Hotel,0,308,2017,July,30,25,4,12,...,No Deposit,9.0,NaN,0,Transient,107.1,0,1,Check-Out,10/08/2017
117829,130432,City Hotel,0,203,2017,July,31,31,3,7,...,No Deposit,9.0,NaN,0,Transient,170.0,0,1,Check-Out,10/08/2017

In [56]:
# 4
mask = df_hotel['arrival_date_month'] == 'July'
df_hotel[mask].sort_values('adults', ascending=False)

,reservation_no,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
116395,128998,City Hotel,0,84,2017,July,29,16,2,1,...,No Deposit,9.0,NaN,0,Transient,234.00,0,3,Check-Out,19/07/2017
94415,107018,City Hotel,0,127,2016,July,32,31,2,2,...,No Deposit,14.0,NaN,0,Transient,253.50,0,1,Check-Out,04/08/2016
93894,106497,City Hotel,0,45,2016,July,31,27,0,1,...,No Deposit,7.0,NaN,0,Transient,223.75,0,2,Check-Out,28/07/2016
26306,38909,Resort Hotel,0,130,2016,July,31,25,1,2,...,No Deposit,240.0,NaN,0,Transient,208.00,0,0,Check-Out,28/07/2016
13027,25630,Resort Hotel,1,318,2017,July,30,28,1,2,...,No Deposit,147.0,NaN,0,Transient,139.68,0,0,Canceled,09/03/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54000,66603,City Hotel,0,193,2016,July,28,4,3,10,...,No Deposit,9.0,NaN,0,Transient,81.82,0,2,Check-Out,17/07/2016
71512,84115,City Hotel,1,315,2017,July,27,7,0,1,...,No Deposit,9.0,NaN,0,Transient,91.85,0,2,Canceled,19/09/2016
54887,67490,City Hotel,0,236,2016,July,31,28,2,4,...,No Deposit,9.0,NaN,0,Transient-Party,6.00,0,1,Check-Out,03/08/2016
54888,67491,City Hotel,1,225,2016,July,31,28,2,4,...,No Deposit,14.0,NaN,0,Transient,79.27,0,1,Canceled,04/06/2016
93754,106357,City Hotel,0,0,2016,July,31,26,0,0,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,26/07/2016

In [70]:
# 5
mask = df_hotel['arrival_date_month'] == 'July'
# Option 1:
df_hotel[mask].sort_values('adults', ascending=False)[['reservation_no', 'arrival_date_month', 'adults']]

# Option 2
df_hotel[mask][['reservation_no', 'arrival_date_month', 'adults']].sort_values('adults', ascending=False)

# Option 3
cols = ['reservation_no', 'arrival_date_month', 'adults']
df_hotel[mask][cols].sort_values('adults', ascending=False)

        reservation_no arrival_date_month  adults
116395          128998               July       4
94415           107018               July       4
93894           106497               July       4
26306            38909               July       4
13027            25630               July       4
...                ...                ...     ...
54000            66603               July       0
71512            84115               July       0
54887            67490               July       0
54888            67491               July       0
93754           106357               July       0

[12661 rows x 3 columns]