<img height='100' src='logotmg.png' width='900' alt='Talia Morchi' title='Data Analyst Course'>
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 2 + 3</h2></center>

In [1]:
import pandas as pd

In [2]:
# Import files we will work with
week1 = pd.read_csv('Restaurant - Week 1 Sales.csv')
week2 = pd.read_csv('Restaurant - Week 2 Sales.csv')
customers = pd.read_csv('Restaurant - Customers.csv')
foods = pd.read_csv('Restaurant - Foods.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Restaurant - Week 1 Sales.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## Concatenation

Concatenation basically glues together DataFrames.

axis = 0 >> attach rows, like union in SQL

axis = 1 >> attach columns, like join in SQL

<img height='200' src='arr_shape.png' width='500' title='Axis Explanation'>

In [ ]:
week1.head(3)

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1

In [ ]:
week2.head(3)

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10

#### Generating new index

In [ ]:
# Concat the two df
# axis = 0 >> attach rows
# axis = 1 >> attach columns
# >> use parameter: ignore_index=True >> generate new index

pd.concat ([week1, week2])

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[500 rows x 2 columns]

#### Using multi index

In [ ]:
# concat df, and use multi index
sales = pd.concat ([week1, week2], keys=['Week_1', 'Week_2'])
sales

            Customer ID  Food ID
Week_1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week_2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [ ]:
# locate rows with multi index
# syntax: df.loc [(external_index, internal_index), column_label]

sales.loc['Week_1']
# sales.loc[('Week_1', 3),'Customer ID']

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

## Append Method

The append() function is used to append rows of other to the end of caller, returning a new object.

Columns in other that are not in the caller are added as new columns

In [ ]:
# Append df at the end of the first df lines
# >> Can use parameter ignore_index = True
week2.append(week1, ignore_index=True)

     Customer ID  Food ID
0            688       10
1            813        7
2            495       10
3            189        5
4            267        3
..           ...      ...
495          413        9
496          926        6
497          134        3
498          396        6
499          535       10

[500 rows x 2 columns]

## Merging

The merge () method allows you to merge DataFrames together using a similar logic as merging SQL Tables together

<img height='800' src='joins_type.png' width='1000' title='Join Types'>

#### Inner join

In [ ]:
# Customer ID 155 has 2 rows - why?
# >> can use parameter: suffixes = [' - A', ' - B']

week1.merge(week2, how = 'inner', on = 'Customer ID')

# week1.merge(week2, how = 'inner', on = 'Customer ID', suffixes = [' - A', ' - B'])

    Customer ID  Food ID_x  Food ID_y
0           537          9          5
1           155          9          3
2           155          1          3
3           503          5          8
4           503          5          9
..          ...        ...        ...
57          945          5          4
58          343          3          5
59          343          3          2
60          343          3          7
61          621          9          6

[62 rows x 3 columns]

In [ ]:
week1[week1['Customer ID'] == 155]

    Customer ID  Food ID
4           155        9
17          155        1

In [ ]:
week2[week2['Customer ID'] == 155]

     Customer ID  Food ID
208          155        3

In [ ]:
# Merging based on two fields - shows only the rows that Customer ID and Food ID is same
week1.merge(week2, how = 'inner', on = ['Customer ID', 'Food ID'])

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5           21        4
6          922        1
7          578        5
8          578        5

In [ ]:
week1[week1['Customer ID'] == 21]

     Customer ID  Food ID
101           21        4
212           21        4

In [ ]:
week2[week2['Customer ID'] == 21]

    Customer ID  Food ID
30           21        4

#### Outer joins

In [ ]:
# Show rows from both df
# Because there are NaN values - the data type converted to float
# >> Can use parameter: indicator = True
merged = week1.merge(week2, how = 'outer', on = 'Customer ID', suffixes = [' - Week 1', ' - Week 2'],
            indicator = True)
merged

     Customer ID  Food ID - Week 1  Food ID - Week 2      _merge
0            537               9.0               5.0        both
1             97               4.0               NaN   left_only
2            658               1.0               NaN   left_only
3            202               2.0               NaN   left_only
4            155               9.0               3.0        both
..           ...               ...               ...         ...
449          855               NaN               4.0  right_only
450          559               NaN              10.0  right_only
451          276               NaN               4.0  right_only
452          556               NaN              10.0  right_only
453          252               NaN               9.0  right_only

[454 rows x 4 columns]

In [ ]:
# To see how many data from each df
merged['_merge'].value_counts()

right_only    197
left_only     195
both           62
Name: _merge, dtype: int64

In [ ]:
# Cut off the rows from both df
# isin ([list_of_values_to _check])
mask = merged['_merge'].isin(['left_only', 'right_only'])
merged[mask]

     Customer ID  Food ID - Week 1  Food ID - Week 2      _merge
1             97               4.0               NaN   left_only
2            658               1.0               NaN   left_only
3            202               2.0               NaN   left_only
6            213               8.0               NaN   left_only
7            600               1.0               NaN   left_only
..           ...               ...               ...         ...
449          855               NaN               4.0  right_only
450          559               NaN              10.0  right_only
451          276               NaN               4.0  right_only
452          556               NaN              10.0  right_only
453          252               NaN               9.0  right_only

[392 rows x 4 columns]

#### Left joins

In [ ]:
# Combine the two df into week1 df
# >> Can use parameter: sort = True

week1 = week1.merge(foods, how = 'left', on = 'Food ID')
# week1 = week1.merge(foods, how = 'left', on = 'Food ID', sort = True)

In [ ]:
week1

     Customer ID  Food ID       Food Item  Price
0            537        9  Chocolate Cake     21
1             97        4            Fish     73
2            658        1         Falafel     20
3            202        2          Malabi     12
4            155        9  Chocolate Cake     21
..           ...      ...             ...    ...
245          413        9  Chocolate Cake     21
246          926        6           Pasta     43
247          134        3        Sandwich     28
248          396        6           Pasta     43
249          535       10           Drink     15

[250 rows x 4 columns]

In [ ]:
week1.head(10)

   Customer ID  Food ID       Food Item  Price
0          537        9  Chocolate Cake     21
1           97        4            Fish     73
2          658        1         Falafel     20
3          202        2          Malabi     12
4          155        9  Chocolate Cake     21
5          213        8           Salad     48
6          600        1         Falafel     20
7          503        5           Pizza     50
8           71        3        Sandwich     28
9          174        3        Sandwich     28

#### Merge based on different column names

When we don't have same column names - we will use left_on and right_on parameters

In [ ]:
customers.head(3)

   ID First Name Last Name  Gender  Company                     Occupation
0   1     Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
1   2   Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
2   3      Roger     Black    Male  Tagfeed              Account Executive

In [ ]:
# When we don't have same column names
# Duplicate column ID, Customer ID
# >> Can use Method: drop('ID', axis = 'columns')

week2 = week2.merge(customers, how = 'left', left_on = 'Customer ID', right_on = 'ID')
# week2 = week2.merge(customers, how = 'left', left_on = 'Customer ID', right_on = 'ID', sort = True).drop('ID', axis = 'columns')

In [ ]:
week2.head()

,Customer ID,Food ID,ID,First Name,Last Name,Gender,Company,Occupation
0,688,10,688,Carl,Williamson,Male,Thoughtmix,Graphic Designer
1,813,7,813,Johnny,Walker,Male,Kayveo,Developer II
2,495,10,495,Deborah,Little,Female,Babbleblab,VP Accounting
3,189,5,189,Roger,Gordon,Male,Skilith,Operator
4,267,3,267,Matthew,Wood,Male,Agimba,Product Engineer

#### Merge based on index

When the df index is its identifier

In [ ]:
# Re import customers and use ID as index
customers = pd.read_csv('Restaurant - Customers.csv', index_col='ID')
customers.head()

   First Name Last Name  Gender  Company                     Occupation
ID
1      Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
2    Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
3       Roger     Black    Male  Tagfeed              Account Executive
4      Steven     Evans    Male     Fatz               Registered Nurse
5        Judy  Morrison  Female  Demivee                Legal Assistant

In [ ]:
# Merge df when in one df the matching column is the index
# we will use right_index = True
sales = week1.merge(customers, how = 'left', left_on = 'Customer ID', right_index = True)

## Stack () Method

The stack() function is used to stack the prescribed level(s) from columns to index. Return a reshaped DataFrame or Series having a multi-level index

In [ ]:
# Re load the hotel csv file - with just some of its columns
hotel = pd.read_csv('hotel_bookings.csv',
                    usecols=['hotel','reservation_no', 'arrival_date_month', 'stays_in_week_nights', 'adults'],
                    index_col=['hotel','reservation_no'])
hotel

                            arrival_date_month  stays_in_week_nights  adults
hotel        reservation_no
Resort Hotel 12603                        July                     0       2
             12604                        July                     0       2
             12605                        July                     1       1
             12606                        July                     1       1
             12607                        July                     2       2
...                                        ...                   ...     ...
City Hotel   131988                     August                     5       2
             131989                     August                     5       3
             131990                     August                     5       2
             131991                     August                     5       2
             131992                     August                     7       2

[119390 rows x 3 columns]

In [ ]:
# stack the columns to index
hotel.stack()
# hotel.stack().unstack()

hotel         reservation_no
Resort Hotel  12603           arrival_date_month        July
                              stays_in_week_nights         0
                              adults                       2
              12604           arrival_date_month        July
                              stays_in_week_nights         0
                                                       ...
City Hotel    131991          stays_in_week_nights         5
                              adults                       2
              131992          arrival_date_month      August
                              stays_in_week_nights         7
                              adults                       2
Length: 358170, dtype: object

In [ ]:
hotel.loc['Resort Hotel', 12603].loc['arrival_date_month']

'July'

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Class Practice 2.5</h1></center>

#### In this practice we will examine the grocery shopping list of two families

1.  The "data" folder contains 3 csv files. Please import the following files into DataFrame objects:
    * Family_1_groceries into df1
    * Family_2_groceries into df2
    * Groceries into gr_df
    
    note: if you want to import from subfolder, the file name should be: 'subfolder_name/file_name.csv'
    

2. Check what each of the DataFrames contains by showing the content of the file
    

3. Combine the shopping data of the two families into new DataFrame name shop_df. Please reindex the DataFrame.


4. Merge the information in gr_df to shop_df, so that the shop_df columns are:
    * Customer no
    * Product Code
    * Description
    * Price
    
    
5. What is the purchase amount of all families?


6. What is the purchase amount of family 1?

=========================================================================================

#### Pactice 2.2 - Solution
#### In this practice we will examine the grocery shopping list of two families

1.  The "data" folder contains 3 csv files. Please import the following files into DataFrame objects:
    * Family_1_groceries into df1
    * Family_2_groceries into df2
    * Groceries into gr_df
    
    note: if you want to import from subfolder, the file name should be: 'subfolder_name/file_name.csv'
    

2. Check what each of the DataFrames contains by showing the content of the file
    

3. Combine the shopping data of the two families into new DataFrame name shop_df. Please reindex the DataFrame.


4. Merge the information in gr_df to shop_df, so that the shop_df columns are:
    * Customer no
    * Product Code
    * Description
    * Price
    
    
5. What is the purchase amount of all families?


6. What is the purchase amount of family 1?

In [ ]:
# 1, 2
df1 = pd.read_csv ('Data/Family_1_groceries.csv')
df1

   Customer no  Product Code
0            1          1003
1            1          1011
2            1          1010
3            1          1008
4            1          1002

In [ ]:
# 1, 2
df2 = pd.read_csv ('Data/Family_2_groceries.csv')
df2

   Customer no  Product Code
0            2          1000
1            2          1004
2            2          1011
3            2          1003
4            2          1009

In [ ]:
# 1, 2
gr_df = pd.read_csv ('Data/Groceries.csv')
gr_df

    Product Code     Description  Price
0           1000           Bread    7.5
1           1001        Soy milk   10.0
2           1002            Eggs   30.0
3           1003          Cheese    5.5
4           1004   Mineral water   12.0
5           1005           Pasta    5.0
6           1006           Bamba    5.0
7           1007         Almonds   20.0
8           1008          Quinoa   15.0
9           1009            Rice   10.0
10          1010           Honey   13.0
11          1011  Dark Chocolate   21.0

In [ ]:
# 3
shop_df = pd.concat ([df1, df2], ignore_index=True)
shop_df

   Customer no  Product Code
0            1          1003
1            1          1011
2            1          1010
3            1          1008
4            1          1002
5            2          1000
6            2          1004
7            2          1011
8            2          1003
9            2          1009

In [ ]:
# 4
shop_df = shop_df.merge (gr_df, how = 'inner', on = 'Product Code')
shop_df

   Customer no  Product Code     Description  Price
0            1          1003          Cheese    5.5
1            2          1003          Cheese    5.5
2            1          1011  Dark Chocolate   21.0
3            2          1011  Dark Chocolate   21.0
4            1          1010           Honey   13.0
5            1          1008          Quinoa   15.0
6            1          1002            Eggs   30.0
7            2          1000           Bread    7.5
8            2          1004   Mineral water   12.0
9            2          1009            Rice   10.0

In [ ]:
# 5
shop_df['Price'].sum()

140.5

In [ ]:
# 6
mask = shop_df['Customer no'] == 1
shop_df[mask]['Price'].sum()

84.5