<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 2 + 3</h2></center>

In [2]:
import numpy as np
import pandas as pd

## Generating random DataFrame

In [3]:
# Generating random matrix
np.random.randint(1, 11, (5,4))

array([[ 3,  3,  9,  4],
       [ 4,  2,  8,  6],
       [ 8,  9,  5,  9],
       [10,  7,  7,  6],
       [ 3,  3,  4,  9]])

In [4]:
# Cast matrix into DataFrame 
# Parameters:  data = random
#              index = list of the index labels
#              columns = list of the column names

df = pd.DataFrame(np.random.randint(1, 11, (5,4)), 
                  index=['A', 'B' ,'C', 'D', 'E'], 
                  columns=['W' ,'X', 'Y', 'Z'])
df

   W  X  Y   Z
A  7  4  8   2
B  7  3  5   1
C  3  6  3   7
D  3  8  5  10
E  5  3  6   1

## Locate rows and columns

loc[start_row:stop:step, start column:stop:step]  = location = the index label >> include last column

iloc[start_row:stop:step, start column:stop:step] = integer location = row number starts with 0 >> not incluse last column

#### Locate row

In [5]:
# Locate single row
df.loc['B']

# Locate range of rows
# df.loc['B':'D']

# locate single row
# df.iloc[1]

W    7
X    3
Y    5
Z    1
Name: B, dtype: int32

#### Locate column

In [6]:
# Locate single column
df.loc[:, 'X']

# Locate range of columns
# df.loc[:, 'W':'Y']

# Locate range of columns (not include )
# df.iloc[:,0:3]

# df['X']
# df[   ['X', 'Y', 'W']   ]

A    4
B    3
C    6
D    8
E    3
Name: X, dtype: int32

#### Locate row and column

In [7]:
# Locate list of rows and columns loc[   [list_of_rows] , [list_of_columns]   ]
df.loc[['A','D'],['W','Z']]

   W   Z
A  7   2
D  3  10

In [8]:
# Locate range of rows and columns loc[   [start_row:stop:step] , [start_column:stop:step]   ]
df.loc['A':'D','W':'Y']

   W  X  Y
A  7  4  8
B  7  3  5
C  3  6  3
D  3  8  5

In [9]:
# Update values ti Null values
df.loc['B','X'] = None
df.loc['D','Y'] = None

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation:

In [10]:
# Select rows that the value in column W, is bigger than 3
df[   df['W']>3   ]

# Select column x of the rows that the value un column W is bigger than 3
# df[ df['W']>3 ]['X']

   W    X    Y  Z
A  7  4.0  8.0  2
B  7  NaN  5.0  1
E  5  3.0  6.0  1

In [11]:
# Define masks variables with the conditions, and them choose df[mask1 | mask2 & mask 3]...
mask = df['W']>3
df[mask]

   W    X    Y  Z
A  7  4.0  8.0  2
B  7  NaN  5.0  1
E  5  3.0  6.0  1

In [12]:
# Combine 2 conditions with and operator
# df[ (df['Y'] > 3) & (df['W'] > 1) ]

mask1 = df['Y'] > 3
mask2 = df['W'] > 1

df[mask1 & mask2]

   W    X    Y  Z
A  7  4.0  8.0  2
B  7  NaN  5.0  1
E  5  3.0  6.0  1

## DataFrame Methods and operations

In [13]:
# Nan (Not a number Null) values are represented as float data type
df

   W    X    Y   Z
A  7  4.0  8.0   2
B  7  NaN  5.0   1
C  3  6.0  3.0   7
D  3  8.0  NaN  10
E  5  3.0  6.0   1

#### Sum

In [14]:
# Sum columns (axis=0) or rows (axis=1)
df.sum(axis=1)

A    21.0
B    13.0
C    19.0
D    21.0
E    15.0
dtype: float64

#### Count

In [15]:
# Count columns (axis=0) or rows (axis=1)
df.count()

W    5
X    4
Y    4
Z    5
dtype: int64

#### Standard deviation

In [16]:
# Calulate standard deviation columns (axis=0) or rows (axis=1)
df.std()

W    2.000000
X    2.217356
Y    2.081666
Z    4.086563
dtype: float64

In [17]:
df['W'] * df['X']

A    28.0
B     NaN
C    18.0
D    24.0
E    15.0
dtype: float64

In [18]:
# Multyple all df values by 5
df * 5

    W     X     Y   Z
A  35  20.0  40.0  10
B  35   NaN  25.0   5
C  15  30.0  15.0  35
D  15  40.0   NaN  50
E  25  15.0  30.0   5

#### Transpose

In [19]:
# Transpose index and columns
df.T

     A    B    C     D    E
W  7.0  7.0  3.0   3.0  5.0
X  4.0  NaN  6.0   8.0  3.0
Y  8.0  5.0  3.0   NaN  6.0
Z  2.0  1.0  7.0  10.0  1.0

#### Drop

In [20]:
# Drop specified labels from rows or columns. Can use inplace=True parameter

# Drop columns (axis = 1)
df.drop('X', axis=1)

# Drop rows (axis=0)
df.drop('B')

   W    X    Y   Z
A  7  4.0  8.0   2
C  3  6.0  3.0   7
D  3  8.0  NaN  10
E  5  3.0  6.0   1

#### Fill Null values

In [21]:
# fill NaN (Null) values with value we choose
df.fillna(0, inplace=True)
df

   W    X    Y   Z
A  7  4.0  8.0   2
B  7  0.0  5.0   1
C  3  6.0  3.0   7
D  3  8.0  0.0  10
E  5  3.0  6.0   1

#### Drop Null values

In [32]:
# Update values ti Null values
df.loc['B','X'] = None
df.loc['D','Y'] = None
df.loc['E'] = None
df

     W     X    Y     Z
A  7.0  None  8.0   2.0
B  7.0  None  5.0   1.0
C  3.0  None  3.0   7.0
D  3.0  None  NaN  10.0
E  NaN  None  NaN   NaN

In [43]:
# Drop all rows with null values
df.dropna()

# >> Use parameter: how='all' >> drop row only if all the values are null
# >> Use parameter: axis=1 >> drop columns with null values
# df.dropna(how='all')
# df.dropna(how='all', subset=['Y'])


# df.dropna(axis=1)

     W     X    Y    Z
A  7.0  None  8.0  2.0
B  7.0  None  5.0  1.0
C  3.0  None  3.0  7.0

#### Change column Data type

In [21]:
# No inplace parameter, so we need to assign the new value
df[['X','Y']] = df[['X','Y']].astype('int')

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Class Practice 2.4</h1></center>

1. Create a DataFrame with 3 columns (column names: Col1, Col2, Col3) and 4 rows (indexes: W, X, Y, Z), with random values between 1 to 20 (include 20)


2. Show rows indexes W and Y


3. Show column: Col2 and Col3


4. Show the secound and third line


5. Show all the rows that the value in col1 is greater then 6 and lower then 18


6. What is the sum of the row values?


7. **Advanced Exercise** - What is the sum of all the numbers in the DataFrame

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Home Practice 3</h1></center>

=========================================================================================

#### Pactice 2.4 - Solution
1. Create a DataFrame with 3 columns (column names: Col1, Col2, Col3) and 4 rows (indexes: W, X, Y, Z), with random values between 1 to 20 (include 20)


2. Show rows indexes W and Y


3. Show column: Col2 and Col3


4. Show the secound and third line


5. Show all the rows that the value in col1 is greater then 6 and lower then 18


6. What is the sum of the row values?


7. **Advanced Exercise** - What is the sum of all the numbers in the DataFrame

In [48]:
# 1
df = pd.DataFrame (np.random.randint (1, 21, (4,3)), 
                   index = ['W', 'X', 'Y', 'Z'],
                   columns = ['Col1', 'Col2', 'Col3'])
df

   Col1  Col2  Col3
W     9    11     8
X    10     1     6
Y    17    14    12
Z    16     6    13

In [49]:
# 2
df.loc[['W','Y']]

   Col1  Col2  Col3
W     9    11     8
Y    17    14    12

In [50]:
# 3
df[['Col2', 'Col3']]

   Col2  Col3
W    11     8
X     1     6
Y    14    12
Z     6    13

In [51]:
# 4
df.iloc[1:3]

   Col1  Col2  Col3
X    10     1     6
Y    17    14    12

In [52]:
# 5
mask = 6 < df['Col1']
mask2 = df['Col1'] <18

df [mask & mask2]

   Col1  Col2  Col3
W     9    11     8
X    10     1     6
Y    17    14    12
Z    16     6    13

In [53]:
# 6
df.sum(axis=1)

W    28
X    17
Y    43
Z    35
dtype: int64

In [54]:
# 7
df.sum().sum()

123