In [7]:
import numpy as np
import pandas as pd

#### Create sample df

In [19]:
df = pd.DataFrame(np.random.randint (1,11,(1000000,6)), 
                  columns=['a','b','c','d','e','f'])
df

        a  b  c  d   e   f
0       3  7  2  1  10   2
1       9  9  6  8   5   8
2       7  8  4  2   5   2
3       2  9  3  3   4   5
4       9  7  1  5   3   1
...    .. .. .. ..  ..  ..
999995  4  9  1  4   1  10
999996  8  4  6  8   2   8
999997  3  5  7  2   6   4
999998  2  8  6  5   5   5
999999  1  7  4  9   9  10

[1000000 rows x 6 columns]

#### Test the logic on one row

In [15]:
sdf = list (df.loc[9])
sdf.sort()
sdf

[1, 8, 8, 9, 9, 9, 10]

In [16]:
sdf[-2]

9

#### Put the logic in function

In [17]:
def get_2nd_max (row):
    sdf = list (row)
    sdf.sort()
    return sdf[-2]

#### Test the function performance

In [20]:
df['calc_2nd_max'] = df.apply(get_2nd_max, axis=1)
df

        a  b  c  d   e   f  calc_2nd_max
0       3  7  2  1  10   2             7
1       9  9  6  8   5   8             9
2       7  8  4  2   5   2             7
3       2  9  3  3   4   5             5
4       9  7  1  5   3   1             7
...    .. .. .. ..  ..  ..           ...
999995  4  9  1  4   1  10             9
999996  8  4  6  8   2   8             8
999997  3  5  7  2   6   4             6
999998  2  8  6  5   5   5             6
999999  1  7  4  9   9  10             9

[1000000 rows x 7 columns]